language: ruby
rvm:
  - 2.1.5
deploy:
  provider: heroku
  api_key:
    secure: <%= ENV['API_SECRET'] %>
  run:
    - 'rake db:migrate'
  app: <%= ENV['HEROKU_APP_NAME'] %>
  on:
    repo: max-borisov/NetguruWorkshop
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - rake db:setup
  - rake db:seed
