language: ruby
rvm:
- 2.1.5
deploy:
  provider: heroku
  api_key:
    secure: <%= ENV['HEROKU_NETGURU_WORKSHOP_API_SECRET_SECURE'] %>
  run:
  - rake db:migrate
  app: netguru-workshop-july-warsaw
  on:
    repo: max-borisov/NetguruWorkshop
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- bundle exec rake db:setup
script:
- bundle exec rspec spec/
